src/common/constants/Navigation.ts, src/common/translations/en.json, src/features/Sync/SyncOutManager.ts, src/features/Sync/SyncSlice.ts, src/ui/screens/settings/MainSettingsScreen.tsx, src/ui/screens/settings/Settings.tsx, src/ui/screens/settings/SyncSettingsScreen.tsx, src/ui/screens/settings/index.ts
Adds `SyncSettingsScreen` for basic sync configuration/credentials.
=> #34 add server settings UI

src/features/Sync/SyncQueueManager.ts, src/features/Sync/SyncSlice.ts
Adds basic logic for clearing sync queue on successful sync.
=> #35 add sync queue clear logic

src/common/services/Database/DatabaseService.ts, src/common/services/Database/entities/SyncConfig.ts, src/features/Sync/SyncOutManager.ts, src/features/Sync/SyncQueueManager.ts, src/features/Sync/SyncSlice.ts, src/ui/containers/DependencyContainer.tsx, src/ui/screens/settings/SyncSettingsScreen.tsx
Refactors sync state, including moving all non-persisted state to redux store.
=> #53 refactor sync state

src/common/services/Database/entities/SyncConfig.ts, src/features/Sync/SyncOutManager.ts, src/features/Sync/SyncSlice.ts, src/ui/screens/settings/SyncSettingsScreen.tsx
Adds basic sync scheduling for periodically pushing sensor data to upstream server.
=> #36 add sync scheduler

src/features/Bluetooth/Download/DownloadManager.ts
Fixes #80 
- Branched from #78 
- The app was checking `== null` but if is no `mostRecentLogTimestamp`, it is `0` not null
- Also added code to create a gap where the best guess is for when a sensor stops recording same as here : https://github.com/openmsupply/mobile/blob/681d2a6b705f8559bb666b3cbbea884564578e0d/src/bluetooth/TemperatureLogManager.js#L60-L73
=> Add check the most recent timestamp is not `0`, and create a gap in logs

src/common/services/UtilService/UtilService.ts, src/features/SensorDetail/Detail/DetailSlice.ts, src/features/index.ts, src/ui/components/SensorChartRow.tsx, src/ui/components/SensorDetailActionBar.tsx, src/ui/components/SensorLastDownloadTime.tsx, src/ui/components/SensorListCumulativeBreachStatus.tsx, src/ui/components/SensorStatus.tsx, src/ui/components/SensorStatusBar.tsx, src/ui/components/buttons/HalfCircleButton.tsx, src/ui/components/modal/ExportDataModal.tsx, src/ui/components/settings/SettingsDateRow.tsx, src/ui/components/settings/SettingsItem.tsx, src/ui/components/settings/SettingsLoadingIndicatorRow.tsx, src/ui/components/settings/SettingsNavigationRow.tsx, src/ui/components/settings/SettingsNumberInputModal.tsx, src/ui/components/settings/SettingsNumberInputRow.tsx, src/ui/components/settings/SettingsStackHeader.tsx, src/ui/components/settings/SettingsTextInputRow.tsx, src/ui/containers/SettingsStackNavigator.tsx, src/ui/hooks/useDatePicker.ts, src/ui/layouts/SensorLogsTable.tsx, src/ui/layouts/SensorRowLayout.tsx, src/ui/layouts/SettingsRowLayout.tsx, src/ui/presentation/Divider.tsx, src/ui/screens/sensors/SensorListScreen.tsx, src/ui/screens/settings/SensorDetailSettingsScreen.tsx, src/ui/screens/settings/TemperatureBreachDetailScreen.tsx
Fixes #95 
- Fixes the cut off settings rows
- Also went offroad and fixed a bunch of typing errors
=> Add typing fixes and style update for cut off settings rows

src/ui/screens/settings/SyncSettingsScreen.tsx
=> Remove validation for username and password

__tests__/common/services/Database/DatabaseService.test.js, __tests__/common/services/FormatService/FormatService.test.js, android/.project, src/common/services/Database/DatabaseService.ts, src/common/services/FormatService/FormatService.ts, src/common/translations/en.json, src/common/types/common.d.ts, src/features/Report/ReportManager.ts, src/features/Report/ReportSlice.ts, src/features/Report/queries.ts, src/features/Report/types.ts, src/features/SensorDetail/Detail/DetailSlice.ts, src/ui/components/modal/ExportDataModal.tsx, src/ui/components/settings/SettingsEditModal.tsx, src/ui/containers/DependencyContainer.tsx, src/ui/presentation/typography/NormalText.tsx, src/ui/presentation/typography/SmallText.tsx
- Can export/email 50,000 logs
- This is ~2mb of data for me- still takes around 10seconds, but it.. works!
=> #143 cant export csv

src/common/services/Database/DatabaseService.ts, src/features/Sync/SyncOutManager.ts, src/features/Sync/SyncQueueManager.ts, src/features/Sync/SyncSlice.ts, src/features/Sync/types.ts, tsconfig.json
- Batching records before sending them
=> #149 batch send records

src/ui/layouts/SensorLogsTable.tsx
Fixes #117 
Adds a debounce to the sort action
=> Debounce sort

src/common/services/UtilService/UtilService.ts, src/common/translations/en.json, src/ui/hooks/useDependency.ts, src/ui/screens/settings/MainSettingsScreen.tsx
=> Add app version into settings

src/common/constants/Dependency.ts, src/common/services/FormatService/FormatService.ts, src/common/services/UtilService/UtilService.ts, src/common/store/index.ts, src/common/translations/en.json, src/features/Entities/BreachConfiguration/BreachConfigurationSlice.ts, src/ui/containers/DependencyContainer.tsx, src/ui/hooks/useDependency.ts, src/ui/screens/settings/MainSettingsScreen.tsx, src/ui/screens/settings/TemperatureBreachSettingsScreen.tsx
=> #119 show more config details

__tests__/common/services/FormatService/FormatService.test.js, src/common/constants/SpecialCharacter.ts, src/common/services/FormatService/FormatService.ts, src/common/translations/en.json, src/ui/components/settings/SettingsTextEditModal.tsx, src/ui/components/settings/SettingsTextInputRow.tsx, src/ui/screens/settings/SyncSettingsScreen.tsx
=> Add hiding of password and correct text

__tests__/common/services/FormatService/FormatService.test.js, src/common/services/Database/DatabaseService.ts, src/common/services/FormatService/FormatService.ts, src/common/store/RootSaga.ts, src/common/translations/en.json, src/common/types/common.d.ts, src/features/Breach/AcknowledgeBreach/AcknowledgeBreachManager.ts, src/features/Breach/AcknowledgeBreach/AcknowledgeBreachSlice.ts, src/features/Breach/index.ts, src/features/Breach/types.ts, src/features/Chart/ChartManager.ts, src/features/Chart/ChartSlice.ts, src/features/Chart/index.ts, src/features/Chart/types.ts, src/features/Entities/Sensor/SensorSlice.ts, src/features/Report/ReportManager.ts, src/features/SensorStatus/SensorStatusSlice.ts, src/features/SensorStatus/index.ts, src/features/SensorStatus/types.ts, src/features/Sync/types.ts, src/ui/components/SensorChartRow.tsx, src/ui/components/SensorStatus.tsx, src/ui/components/modal/AcknowledgeBreachModal.tsx, src/ui/components/settings/SettingsTextInputRow.tsx, src/ui/layouts/SensorRowLayout.tsx, src/ui/layouts/SensorStatusLayout.tsx, src/ui/screens/sensors/SensorListScreen.tsx, src/ui/screens/settings/SyncSettingsScreen.tsx
=> #181 acknowledge modal

src/features/SensorStatus/SensorStatusManager.ts, src/features/SensorStatus/types.ts, src/ui/presentation/icons/Battery.tsx
=> Add correct battery thresholds

android/app/build.gradle, android/app/src/debug/java/com/cce/ReactNativeFlipper.java
.. 🤷 
Something about OkHttp version mismatching... https://github.com/facebook/react-native/issues/28481
=> Get android 11 to work

src/features/Chart/ChartSlice.ts, src/ui/components/modal/AcknowledgeBreachModal.tsx, src/ui/layouts/SensorLogsTable.tsx, src/ui/presentation/Chart.tsx, src/ui/screens/sensors/SensorListScreen.tsx
Fixes #191 
- Removes the incorrect multiplier
- Changed the formatting to be nicerer
=> #191 sensor log table timestamps

src/features/Chart/ChartSlice.ts, src/ui/presentation/Chart.tsx, src/ui/screens/sensors/SensorListScreen.tsx
Fixes #190 
This way, when the sensors are fetched from the DB, the chart slice can use the ids found to update the loading status initially.
=> Add updated chart status

android/build.gradle
Fixes #227 
With reference to https://github.com/openmsupply/mobile/pull/4988
=> build settings

src/common/services/Database/DatabaseService.ts, src/features/Sync/SyncOutManager.ts, src/features/Sync/SyncSlice.ts
Fixes #294 
Makes requests for sensor, temparature log & temperature breach if there is/are data in the syncLog to be pushed.
=> #294 fix empty cca app sync request

package.json, src/features/Sync/SyncSlice.ts
Fixes #307 
Not sure how this one slipped in!
Here's a release build - which might help with testing
[mSupplyColdChain-0_5_7-rc1-armeabi-v7a-release.apk.zip](https://github.com/user-attachments/files/17050938/mSupplyColdChain-0_5_7-rc1-armeabi-v7a-release.apk.zip)
=> Not syncing records

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/msupplycoldchain/MainActivity.java
Fixes #310
Added in code to manually request permissions and this is working for me; am prompted for nearby devices and the app finds sensors immediately.
On first install of the app, after asking permissions, the app closes. On reopening, everything is fine. 
Can you confirm if this happens for you too? Is that an acceptable trade-off? It's only the first time the app opens 🤷 
There is a [release apk](https://drive.google.com/file/d/1w5kcRlGkn_oPMgav43plitg0wCPOjzuS/view?usp=drive_link) available for testing
=> Prompt for Nearby Devices permission
