src/features/Bluetooth/Download/DownloadSlice.ts
Fixes #78 
Extra `take` here. The saga is already invoked when the same action is dispatched, so this is blocking, waiting for the action to be dispatched a second time, which is not what we want
=> #78 App not passively downloading

__tests__/common/constants/__snapshots__/Chart.test.js.snap, src/common/constants/Chart.ts, src/ui/components/SensorTemperatureStatus.tsx, src/ui/layouts/SensorStatusLayout.tsx
Fixes #89 
Updated the layout, so that the boxes are vertically aligned. Aligned the breach icon and right-aligned the updated text as that looked better.
After aligning the temps, went with 1dp display as that looks more consistent. 
Some examples below
Have updated the chart interpolation type as well, along the lines of https://github.com/openmsupply/mobile/pull/3567 as I saw some of the same strangeness in the screenshots provided.
As noted, the row separator appears to have been removed, and the cold breach text ( was going to replace `-` with `&` but no need now )
Could recreate the other issues.
=> #89 sensor display tweaks

src/common/constants/Chart.ts, src/ui/components/SensorChartRow.tsx, src/ui/layouts/SensorRowLayout.tsx, src/ui/presentation/Chart.tsx
Fixes #89 
Resolves the problem with the x-axis appearing mid-way up the chart when it has both positive and negative values to display.
The result is this: which shows all-positive, all-negative and a mix:
Also removed the fixed row height on the chart, as that was causing the charts to bump into each other.
=> x-axis vertical alignment

src/ui/containers/MainTabNavigator.tsx, src/ui/screens/sensors/Sensors.tsx
Fixes #150 
With the behaviour for back button specified in the bottom tab navigator, was unable to repro.
Could repro prior to the change, so this may resolve the problem.
=> Handle back in bottomTabBar

src/ui/components/SensorTemperatureStatus.tsx, src/ui/presentation/icons/LowBattery.tsx
Fixes #155 
Updated the flex usage - this was behaving very strangely due to the rendering of all three icons, whether used or not. They were taking up space when not shown, causing layout issues.
Also made the battery icon smaller, this was the only usage, so have set the default size to be what I want.
Results:
=> tidy flex usage for status

src/ui/layouts/SensorDetailScreenLayout.tsx, src/ui/screens/settings/DevSettingsScreen.tsx
Fixes #55 
Removes the developer sync section.
The section in sync settings has been renamed, but the function is the same.
=> remove dev sync records section

src/common/types/common.d.ts, src/features/Chart/ChartSlice.ts, src/features/Entities/Sensor/SensorSlice.ts, src/features/SensorStatus/SensorStatusManager.ts, src/features/SensorStatus/SensorStatusSlice.ts
Fixes #159 
Maaaybe this is ugly and silly. I'm not sure. I think it's good to try and have the keys of the query match a typed result, I guess!
This is changing and tidying the query as well as the result to what is actually being used currently.
The other change to the query is to allow passing in a different filter for sensors. I plan to do another PR which will allow me to pass in a filter for just the active sensors, and then we can hydrate the app and get all the status' at once to hopefully reduce load time a little
=> #159 sensor status types

__tests__/common/services/UtilService/UtilService.test.js, src/common/services/Bluetooth/BleService.ts, src/common/services/UtilService/UtilService.ts
Fixes #174 
I changed `75` to `70` 🥇 
( also adding a floor to the result, since the test changes resulted in real numbers with lots of decimal places )
=> change battery range lower bound to 70

android/app/src/main/AndroidManifest.xml
Fixes #173 
In more recent android os versions, you need to explicitly allow for http requests.
You can (preferred way) specify the exact domain for the http request, but since we won't know the domains, have just enabled for everything.
=> Add sending of clear traffic

__tests__/common/constants/__snapshots__/Reducer.test.js.snap, __tests__/common/services/FormatService/FormatService.test.js, __tests__/common/services/UtilService/UtilService.test.js, __tests__/features/Bluetooth/BatteryObserver/BatteryObserverSlice.test.js, __tests__/features/Bluetooth/Download/DownloadManager.test.js, __tests__/features/Bluetooth/Program/ProgramSlice.test.js, __tests__/features/Breach/ConsecutiveBreachManager/ConsecutiveBreachManager.test.js, __tests__/features/SensorStatus/SensorStatusManager.test.js, src/common/constants/Milliseconds.ts, src/common/services/FormatService/FormatService.ts, src/common/services/UtilService/UtilService.ts, src/features/Bluetooth/BatteryObserver/BatteryObserverSlice.ts, src/features/Bluetooth/Download/DownloadManager.ts, src/features/Bluetooth/Program/ProgramSlice.ts, src/features/Breach/ConsecutiveBreach/ConsecutiveBreachManager.ts, src/features/Entities/Sensor/SensorManager.ts, src/features/SensorDetail/Detail/DetailSlice.ts, src/ui/components/MainHeader.tsx, src/ui/components/settings/SettingsAddSensorModal.tsx, src/ui/components/settings/SettingsAddSensorRow.tsx, src/ui/hooks/useTime.ts, src/ui/layouts/SensorLogsTable.tsx
- Have refactored all* the uses of moment to be using either the `UtilService` or `FormatService` so there are centralised places to change the library.
- *There are a couple instances which required more refactoring to remove the use of moment- specifically places where the date range moment plugin was used: `twix` and also where the date range picker actually internally uses moment.. theres an issue to replace the date range picker because it's not great, so will leave this for now, this is plenty big enough..
- Didn't actually remove moment. I was thinking of waiting until whatever package we decide on for open msupply can be used here, if there's a stronger reason. The changes here make it really easy to do it.
- Updated tests. Removed a couple which were failing which either need …
=> #85 replace moment

src/ui/hooks/usePowerState.ts
#194 
So this is a bit hacky. I didn't want to add yet another package or touch java to add a listener to the actual android event, so instead.. just polling. Too hacky?
=> Add different battery level listening implementation

src/features/SensorDetail/LogTable/LogTableSlice.ts
Fixes #201 
I think the offset is just being incremented twice after the initial fetch (once on fetchSuccess, and again on fetchMore) so far with local testing it seems like this should address the issue reported.
=> #201 Don't increment offset after first fetch (getMore will do the increment)

README.md, package.json, src/common/constants/Setting.ts, src/common/constants/Timeout.ts, src/common/constants/index.ts, src/common/services/Database/DatabaseService.ts, src/common/services/FormatService/FormatService.ts, src/features/Entities/Setting/SettingManager.ts, src/features/Entities/Setting/SettingSlice.ts, src/features/Sync/SyncOutManager.ts, src/features/Sync/SyncSlice.ts, src/features/Sync/types.ts, src/ui/screens/settings/SyncSettingsScreen.tsx
Closes #252 
By default axios (our API request framework) doesn't timeout network connections if they hang.
It seems likely that during the server backup, since mSupply Server API Requests simply hang and the Sync `Saga` simply hangs waiting for the connection to finish. 
If the connection is hung for a long time (say 20minutes) the connection appears to be timed out somewhere in the OS or network layer, but this isn't correctly handled in our application.
With this change, we've added a request timeout which returns an error if the connection can't be made to the server.
We've also slightly improved some of the logging and error handling, including a sync status section in the configuation.
=> 252 cca sync stops during server backup tablet needs to be restarted

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/msupplycoldchain/MainActivity.java, android/app/src/main/java/com/msupplycoldchain/MainApplication.java, package.json
Fixes #255 
This is the 'please drain my battery' option 😉 
This will implement a [wakelock](https://developer.android.com/training/scheduling/wakelock) to allow the app to keep interacting and uploading data even when the screen is being saved.
To test: configure a sensor and sync. Start the app, plug the tablet in and see if it continues to sync over 2+ days.
=> Keep app awake

src/features/Bluetooth/Download/DownloadSlice.ts, src/features/Monitor/MonitorSlice.ts
Don't restart bluetooth if there's a download in progress.
Might help with the missing data issues we've seen?
=> Don't restart bluetooth while downloading

package.json, src/common/services/UtilService/UtilService.ts, src/features/Entities/Sensor/SensorManager.ts, yarn.lock
Closes #273 
Hashes the Mac Address to get a unique ID for the sensor.
I'm now wondering if we should just use the mac address directly instead though?
Not sure what we gain by hashing?
=> 273 consistent id for sensors when added

src/features/Sync/SyncSlice.ts
Fixes #290 
Sends the temperature breach records first, then temperature logs, which means the temperature logs changes won't fail with a foreign key constraint.
Note: Accidentally committed this to the develop branch 🫣
See: https://github.com/msupply-foundation/open-msupply/pull/2901 for more context if required
=> Re-order temperature_log and temperature_breach integration sync

src/features/Sync/SyncSlice.ts, src/features/Sync/types.ts, src/ui/screens/settings/SyncSettingsScreen.tsx
Added a check into the server URL test which checks:
* that the server returns `{ success: true }` when you try to login
* that the server returns an empty array if you PUT an empty array of sensors
the second check might not be strictly necessary - but is a useful test to see if this is a cold chain API that we are looking at
To test? I tried using a dashboard URL and that returned 404, so did not repro the issue.
However, using the [PostTestServer](https://posttestserver.dev/p/3vwma67tmg21zd4t) works - as this returns a 200 response regardless of what you post to it.
=> Test sensor url

src/ui/layouts/SettingsEditModalLayout.tsx
Fixes #286 
Have removed the keyboard height being added to the padding on `FullScreenModal` as this isn't required for me, and causes the issue of the inputs being pushed out of sight.
To test: simply try to adjust the username or password in sync settings.
There is a [release apk](https://drive.google.com/file/d/1wC9wluSlpvjqgEiCHXYgcuJEc19LUDTd/view?usp=drive_link) available for testing
=> Keyboard appearance pushes input off screen

.sdkmanrc, README.md, src/common/services/Database/DatabaseService.ts, src/common/services/LoggerService/FileLoggerService.ts, src/common/services/UtilService/index.ts, src/features/Bluetooth/Program/ProgramSlice.ts, src/features/Entities/Setting/SettingManager.ts, src/features/Entities/Setting/SettingSlice.ts, src/ui/containers/DependencyContainer.tsx, src/ui/screens/settings/DebugSettingsScreen.tsx
Fixes #322 
I couldn't figure out a good pattern for enabling it on start up.
After various different attempts I've put it into the DependancyContainer.
Probably not the right place but figure if it's working, it's better then nothing?
=> Debug logging
